# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Vincentqyw"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'
logging_path: 'run.log'
update_code_link_num: 200

# keywords to search
keywords:
  "Recsys":
    description: "推荐系统"
    categories:
      - cs.CL
      - cs.IR
      - cs.LG
      - cs.AI
    query: >
      (ti:"recommendation system" OR abs:"recommendation system" OR abs:"recsys" OR abs:"Recommender system" OR ti:"advertising system" OR abs:"advertising system" OR abs:"advertising" OR abs:"search engine")
    max_results: 20
    sort_by: "submitted_date"
    sort_order: "descending"

  "Recsys LLM":
    description: "推荐系统&大模型"
    categories:
      - cs.CL
      - cs.IR
      - cs.LG
      - cs.AI
    query: >
      (ti:"recommendation system" OR abs:"recommendation system" OR abs:"recsys" OR abs:"Recommender system" OR ti:"advertising system" OR abs:"advertising system" OR abs:"advertising" OR abs:"search engine")
      AND
      (ti:"large language model" OR abs:"large language model" OR ti:LLM OR abs:LLM OR ti:"language model" OR abs:"language model")
    max_results: 20
    sort_by: "submitted_date"
    sort_order: "descending"
  
  "LLM":
    description: "大模型论文"
    categories:
      - cs.CL
      - cs.IR
      - cs.LG
      - cs.AI
    query: >
      (ti:"large language model" OR abs:"large language model" OR ti:LLM OR abs:LLM OR ti:"language model" OR abs:"language model")
      AND
      (abs:"chatgpt" OR abs:"openai" OR abs:"gpt" OR abs:"claude" OR abs:"gemini" OR abs:"llama" OR abs:"mistral" OR abs:"deepseek" OR abs:"moonshot" OR abs:"kimi" OR abs:"internlm" OR abs:"qwen" OR abs:"baichuan" OR abs:"glm" OR abs:"pangu" OR abs:"minimax" OR abs:"minimaxgpt" OR abs:"doubao" OR abs:"bytedance" OR abs:"google" OR abs:"apple" OR abs:"deepmind")
    max_results: 30
    sort_by: "submitted_date"
    sort_order: "descending"
  
#  graph_rec:
#    description: "图神经网络在推荐系统中的应用，在 cs.LG 中检索"
#    categories:
#      - cs.LG
#    query: >
#      (ti:"graph neural network" OR abs:"graph neural network" OR ti:GNN OR abs:GNN)
#      AND
#      (ti:recommendation OR abs:recommendation)
#    max_results: 10
#    sort_by: "submitted_date"
#    sort_order: "descending"
